id: A597A9588
title: Toh_179-Teaching_The_Relative_and_Ultimate_Truths-v1
type: translation
pechas:
- ICE4D99C4
- I6107BA2E
source_metadata:
  creationtool: Olifant
  creationtoolversion: 3.0.8.0
  datatype: unkown
  segtype: paragraph
  adminlang: BO
  srclang: BO
  o-tmf: Olifant
  creationdate: 20170418T102617Z
  creationid: CloudedCat
  changedate: 20170418T103530Z
  changeid: CloudedCat
  title: Toh_179-Teaching_The_Relative_and_Ultimate_Truths-v1
alignment_to_base:
  ICE4D99C4/9593: '6764'
  I6107BA2E/3969: '6764'
